name: ${project.name}
version: ${project.version}
main: com.igor.blockhunt.BlockHuntPlugin
api-version: '1.21'
authors: [Igor]
description: Disguise as a block and become solid when standing still.
softdepend: [LibsDisguises]

commands:
  blockhunt:
    description: Main command for BlockHunt plugin.
    aliases: [bh]

permissions:
  blockhunt.admin:
    description: Allows resetting all disguises and other admin commands.
    default: op
  blockhunt.givewand:
    description: Allows the user to get the Block Hunt wand.
    default: op